config/routes.rb
Rails.application.routes.draw do

  resources :cats
  resources :cat_rental_requests, only: [:create, :new] do
    post "approve", on: :member
    post "deny", on: :member
  end
  resource :user, only: [:create, :new, :show]
  resource :session, only: [:new, :create, :destroy]

  root to: redirect("/cats")
end

app/models/cat.rb
require 'action_view'

class Cat < ActiveRecord::Base
  include ActionView::Helpers::DateHelper

  CAT_COLORS = %w(black white orange brown)

  has_many(
    :rental_requests,
    class_name: "CatRentalRequest",
    dependent: :destroy
  )

  belongs_to(
    :owner,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: "User"
  )

  validates(
    :birth_date,
    :color,
    :name,
    :sex,
    :user_id,
    presence: true
  )

  validates :color, inclusion: CAT_COLORS
  validates :sex, inclusion: %w(M F)


  def age
    time_ago_in_words(birth_date)
  end
end

app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base

  STATUSES = %w(PENDING APPROVED DENIED)

  belongs_to :cat,
  primary_key: :id,
  foreign_key: :cat_id,
  class_name: "Cat"

  belongs_to :user,
  primary_key: :id,
  foreign_key: :user_id,
  class_name: "User"

  after_initialize :assign_pending_status

  validates(
    :cat_id,
    :start_date,
    :end_date,
    :status,
    :user_id,
    presence: true
  )

  validates :status, inclusion: STATUSES
  validate :does_not_overlap_approved_requests
  validate :start_date_precedes_end_date

  def denied?
    self.status == "DENIED"
  end


  def approve!
    raise "not pending" unless self.status == "PENDING"
    transaction do
      self.status = "APPROVED"
      self.save

      overlapping_pending_requests.update_all(status: "DENIED")
    end
  end

  def deny!
    self.status = "DENIED"
    self.save!
  end

  def pending?
    self.status == "PENDING"
  end

  protected

  def assign_pending_status
    self.status ||= "PENDING"
  end

  def overlapping_requests
    CatRentalRequest
      .where("(:id IS NULL) OR (id != :id)", id: self.id)
      .where(cat_id: cat_id)
      .where(<<-SQL, start_date: start_date, end_date: end_date)
       NOT( (start_date > :end_date) OR (end_date < :start_date) )
SQL
  end

  def overlapping_approved_requests
    overlapping_requests.where("status = 'APPROVED'")
  end

  def overlapping_pending_requests
    overlapping_requests.where("status = 'PENDING'")
  end

  def does_not_overlap_approved_requests
    return if self.denied?
    unless overlapping_approved_requests.empty?
      errors[:base]<< "Request conflicts with existing approved request"
    end
  end

  def start_date_precedes_end_date
    return if start_date.nil? || end_date.nil?
    unless self.start_date < self.end_date
      errors[:base] << "Start date must precede end date"
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password

  validates :username, :password_digest, :session_token, presence: true
  validates :session_token, :username, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  after_initialize :ensure_session_token


  has_many(
    :cats,
    class_name: "Cat",
    dependent: :destroy
  )

  has_many :rental_requests,
  class_name: "CatRentalRequest",
  dependent: :destroy




  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)

    return nil if user.nil?

    user.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    self.password_digest.is_password?(password)
  end

  def password_digest
    BCrypt::Password.new(super)
  end

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64
    self.save!
  end

  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user


  def current_user
    return nil if self.session[:session_token].nil?
    @user ||= User.find_by(session_token: self.session[:session_token])
  end

  def log_in!(user)
    user.reset_session_token!
    self.session[:session_token] = user.session_token
  end

  def log_out!
    self.session[:session_token] = nil
  end

  def require_user!
    redirect_to new_session_url if current_user.nil?
  end


end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController


  def new
    @rental_request = CatRentalRequest.new
    render :new
  end

  def create
      @rental_request = CatRentalRequest.new(cat_rental_request_params)
      @rental_request.user_id = current_user.id
      if @rental_request.save
        redirect_to cat_url(@rental_request.cat)
      else
        flash.now[:errors] = @rental_request.errors.full_messages
        render :new
      end
    end

  def approve
    @rental_request = CatRentalRequest.find(params[:id])

    @rental_request.approve!
    redirect_to cat_url(@rental_request.cat)
  end

  def deny
    @rental_request = CatRentalRequest.find(params[:id])

    @rental_request.deny!

    redirect_to cat_url(@rental_request.cat)

  end




  private




  def cat_rental_request_params
    params.require(:cat_rental_request)
      .permit(:cat_id, :end_date, :start_date, :status)
  end

end

app/controllers/cats_controller.rb
class CatsController < ApplicationController

  before_action :require_user!, only: [:new, :create, :edit, :update]
  before_action :validate_ownership, only: [:edit, :update]


  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def new
    @cat = Cat.new
    render :new
    #/cats/new
    #show a form to craete a new object
  end

  def create
    @cat = current_user.cats.new(cat_params)
    if @cat.save
      redirect_to cat_url(@cat)
    else
      flash.now[:errors] = @cat.errors.full_messages
      render :new
    end
  end

  def edit
    @cat = current_user.cats.find(params[:id])
    render :edit
  end

  def update
    @cat = current_user.cats.find(params[:id])
    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      render :edit
    end
  end


  private

  def cat_params
    params.require(:cat).permit(:name, :birth_date, :color, :sex, :description)
  end

  def validate_ownership
    cat = Cat.find(params[:id])
    unless current_user.cats.include?(cat)
      flash.now[:errors] = "You cannot edit this cat. You are not the owner"
      redirect_to cats_url
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create

    @user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password])

    if @user.nil?

      render :new
    else
      log_in!(@user)
      redirect_to cats_url
    end
  end

  def destroy
    current_user.reset_session_token!
    log_out!
    redirect_to new_session_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in!(@user)
      redirect_to user_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    if current_user.nil?
      redirect_to new_session_url
    else
      @user = current_user
      render :show
    end

  end

  protected

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cat_rental_requests/new.html.erb
<h1>Create Rental Request</h1>

  <%= render "shared/errors" %>

<form action="<%= cat_rental_requests_url %>" method="post">

  <input
  type="hidden"
  name="authenticity_token"
  value="<%= form_authenticity_token %>">

  <label for="cat_rental_request_cat_id">Cat</label>
  <select name="cat_rental_request[cat_id]"
          id="cat_rental_request_cat_id">
    <option></option>
    <% Cat.all.each do |cat| %>
      <% selected = @rental_request.cat_id == cat.id %>
      <option <%= selected ? "selected" : "" %>
              value="<%= cat.id %>">
        <%= cat.name %>
      </option>
    <% end %>
  </select>
  <br>

  <label for="cat_rental_request_start_date">Start Date</label>
  <input
    type="date"
    name="cat_rental_request[start_date]"
    value="<%= @rental_request.start_date %>"
    id="cat_rental_request_start_date">
  <br>

  <label for="cat_rental_request_end_date">End Date</label>
  <input
    type="date"
    name="cat_rental_request[end_date]"
    value="<%= @rental_request.end_date %>"
    id="cat_rental_request_end_date">
  <br>

  <input type="submit">



<!--
<h1>Rent a cat!</h1>

<form action="<%= cat_rental_requests_url %>" method="post">

  <label for "cat_rental_request_cat_id">Select a cat to rent:</label>
  <select name="cat_rental_request[cat_id]"
          id="cat_rental_request_cat_id">
    <option></option>
    <% Cat.all.each do |cat| %>
      <% selected = @rental_request.cat_id == cat.id %>
      <option <%= selected ? "selected" : "" %>
          value="<%cat.id%>">
      <%= cat.name %></option>
    <% end %>
  </select>
  <br>
  <br>

  <label  for="cat_rental_request_start_date">Rental start date</label>
  <input type="date"
         name="cat_rental_request[start_date]"
         id="cat_rental_request_start_date"
         value="<%= @rental_request.start_date %>">
         <br>
  <label  for="cat_rental_request_end_date">Rental end date</label>
  <input type="date"
         name="cat_rental_request[end_date]"
         id="cat_rental_request_end_date"
         value="<%= @rental_request.end_date %>">


  <br>
  <br>
  <input type="submit" value="Request cat rental">

</form> -->

app/views/cats/_form.html.erb
<% action_url = @cat.persisted? ? cat_url(@cat) : cats_url %>
<% form_method = @cat.persisted? ? "PATCH" : "POST" %>
<% submit_text = @cat.persisted? ? "Update #{@cat.name}" : "Create Cat!" %>

<form action="<%= action_url %>" method="POST">
  <input type="hidden" name="_method" value="<%= form_method %>">


  <input
  type="hidden"
  name="authenticity_token"
  value="<%= form_authenticity_token %>">

  <label for="cat_name">Cat name</label>
  <input type="text" name="cat[name]" id="cat_name" value= "<%= @cat.name %>">
  <br>

  <label for="cat_sex_male">Male</label>
  <input type="radio"
         name="cat[sex]"
         id="cat_sex_male"
         value="M"
         <%= "checked" if @cat.sex == "M" %>>
  <br>

  <label for="cat_sex_female">Female</label>
  <input type="radio"
         name="cat[sex]"
         id="cat_sex_female"
         value="F"
         <%= "checked" if @cat.sex == "F" %>>
  <br>

  <label for="cat_color">Cat's coat color</label>
  <select name="cat[color]" id="cat_color">
    <% Cat::CAT_COLORS.each do |cat_color| %>
      <option value="<%= cat_color %>"
        <%= "selected" if @cat.color == cat_color %>>
        <%= cat_color %>
      </option>
    <% end %>
  </select>
  <br>

  <label for="cat_bday">Cat's birth date</label>
  <input type="date" name="cat[birth_date]" id="cat_bday" value= "<%= @cat.birth_date %>">
  <br>

  <label>
     Description
     <textarea name="cat[description]"><%= @cat.description %></textarea>
  </label>


  <input type="submit" value="<%= submit_text %>">
</form>

app/views/cats/_request_tr.html.erb
<tr>
  <td><%= request.start_date %></td>
  <td><%= request.end_date %></td>
  <td><%= request.user.username %></td>
  <td>
    <% if request.pending? %>
      <%= button_to "Approve", approve_cat_rental_request_url(request) %>
      <%= button_to "Deny", deny_cat_rental_request_url(request) %>
    <% else %>
      <%= request.status %>
    <% end %>
  </td>
</tr>

app/views/cats/edit.html.erb
<h1> Update <%= @cat.name %>! </h1>

<%= render "form" %>

app/views/cats/index.html.erb
<h1>KITTEHS</h1>


  <ul>
    <% @cats.each do |cat| %>
      <li><%= link_to cat.name, cat_url(cat) %></li>
    <% end %>
  </ul>

<h2><a href="/cats/new" >Create New Cat</a></h2>
<h2><a href="<%= new_cat_rental_request_url %>">Rent a cat!</a>

app/views/cats/new.html.erb
<h1>Create a cat!</h1>

<%= render "shared/errors" %>

<%= render "form" %>

app/views/cats/show.html.erb
<h1><%= @cat.name %></h1>

<table>
  <% [:age, :birth_date, :color, :sex, :description].each do |attribute|%>
    <tr>
      <td><%= attribute %> </td>
      <td><%=@cat.send(attribute) %>
    </tr>
  <% end %>
</table>
<br>


<h2> Rental Requests </h2>
<table>

    <tr>
      <th>Start Date</th>
      <th>End Date</th>
      <th>Requester</th>
      <th>Status</th>
    </tr>
  <% @cat.rental_requests.order("start_date").each do |request| %>
    <%= render "request_tr", request: request %>
  <% end %>
</table>

<ul>
  <li><a href="<%= edit_cat_url(@cat) %>">Edit <%= @cat.name %></a></li>
  <li><a href="<%= cats_url %>">Index</a></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NinetyNineCats</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% unless current_user.nil? %>
    <h2><%= current_user.username %></h2>
    <%= render "shared/log_out_button" %>
  <% else %>
    <%= render "shared/log_in_button" %>
    <%= render "shared/sign_up_button" %>
  <% end %>

<%= yield %>

</body>
</html>

app/views/session/new.html.erb
<h1>Login!</h1>

<form action="<%= session_url %>" method="post">

  <input
  type="hidden"
  name="authenticity_token"
  value="<%= form_authenticity_token %>">

  <%= render "shared/errors" %>

  <label for="user_username">Username</label>
  <input type="text" name="user[username]" id="user_username">
  <br>

  <label for="user_password">Password</label>
  <input type="password" name="user[password]" id="user_password">
  <br>

  <input type="submit" value="Login!">
</form>

app/views/shared/_errors.html.erb
<% if flash[:errors] %>
  <ul>
  <% flash[:errors].each do |error| %>
    <li><%= error %></li>
  <% end %>
</ul>
<% end %>

app/views/shared/_log_in_button.html.erb
<form action="<%= new_session_url %>" method="GET">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">
  <input type="submit" value="Log in!">
</form>

app/views/shared/_log_out_button.html.erb
<form action="<%= session_url %>" method="POST">
  <input type="hidden" name="_method" value="DELETE">

  <input
  type="hidden"
  name="authenticity_token"
  value="<%= form_authenticity_token %>">
  
  <input type="submit" value="Logout!">
</form>

app/views/shared/_sign_up_button.html.erb
<form action="<%= new_user_url %>" method="GET">

  <input
  type="hidden"
  name="authenticity_token"
  value="<%= form_authenticity_token %>">
  
  <input type="submit" value="Sign up!">
</form>

app/views/users/new.html.erb
<h1> Sign up! </h1>

  <%= render 'shared/errors' %>

<form action="<%= user_url %>" method="POST">


  <input
  type="hidden"
  name="authenticity_token"
  value="<%= form_authenticity_token %>">
  
  <label for="user_username">Username</label>
  <input type="text"
         name="user[username]"
         id="user_username"
         value="<%= @user.username %>">
  <br>
  <label for="user_password">Password</label>
  <input type="password"
         name="user[password]"
         id="user_password">
  <br>

  <input type="submit" value="Sign up!">

</form>

app/views/users/show.html.erb
<h1>Welcome, <%= current_user.username %></h1>